# Generated by Django 3.2.3 on 2024-09-26 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Название породы"
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Tiny", "Крошечная"),
                            ("Small", "Маленькая"),
                            ("Mediun", "Среднего размера"),
                            ("Large", "Большая"),
                        ],
                        max_length=15,
                        verbose_name="Размер собаки",
                    ),
                ),
                (
                    "friendliness",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Дружелюбность (от 1 до 5)",
                    ),
                ),
                (
                    "trainability",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Обучаемость (от 1 до 5)",
                    ),
                ),
                (
                    "shedding_amount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Линька (от 1 до 5)",
                    ),
                ),
                (
                    "exercise_needs",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Потребность в активности (от 1 до 5)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Порода собаки",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="Имя собаки")),
                ("age", models.IntegerField(verbose_name="Возраст собаки")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "мужской"), ("female", "женский")],
                        max_length=7,
                        verbose_name="Пол собаки",
                    ),
                ),
                ("color", models.CharField(max_length=15, verbose_name="Цвет собаки")),
                (
                    "favorite_food",
                    models.CharField(max_length=100, verbose_name="Любимая еда"),
                ),
                (
                    "favorite_toy",
                    models.CharField(max_length=100, verbose_name="Любимая игрушка"),
                ),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breed",
                        to="api.breed",
                        verbose_name="Порода собаки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Собака",
                "verbose_name_plural": "Собаки",
                "ordering": ("name",),
            },
        ),
    ]
