# Generated by Django 3.2.3 on 2024-10-03 09:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',), 'verbose_name': 'Порода собаки', 'verbose_name_plural': 'Породы собак'},
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название породы'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='shedding_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Количество шерсти при линьке (от 1 до 5)'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='size',
            field=models.CharField(choices=[('tiny', 'крошечная'), ('small', 'маленькая'), ('medium', 'средняя'), ('large', 'большая')], max_length=20, verbose_name='Размер собаки'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breed', to='api.breed', verbose_name='Порода собаки'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Окрас собаки'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('male', 'мужской'), ('female', 'женский')], max_length=10, verbose_name='Пол собаки'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя собаки'),
        ),
    ]
